"""initial schema

Revision ID: 72bd0b60a206
Revises: 
Create Date: 2026-01-09 14:31:50.322184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72bd0b60a206'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('baseline_sales', sa.Integer(), nullable=True),
    sa.Column('baseline_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('result_sales', sa.Integer(), nullable=True),
    sa.Column('result_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sales_change_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('revenue_change_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_change_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_product_id'), 'experiments', ['product_id'], unique=False)
    op.create_index(op.f('ix_experiments_review_date'), 'experiments', ['review_date'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'warehouse_name', 'snapshot_date', name='uq_inventory_snapshot')
    )
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshot_date'), 'inventory', ['snapshot_date'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_created_at'), 'price_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_price_history_product_id'), 'price_history', ['product_id'], unique=False)
    op.create_table('price_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recommended_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('change_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('score_up', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('score_down', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('baseline_sales_7d', sa.Integer(), nullable=True),
    sa.Column('baseline_revenue_7d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_id')
    )
    op.create_index(op.f('ix_price_recommendations_product_id'), 'price_recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_price_recommendations_status'), 'price_recommendations', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('offer_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_margin_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_offer_id'), 'products', ['offer_id'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=True)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('returns_qty', sa.Integer(), nullable=False),
    sa.Column('returns_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'date', name='uq_sales_product_date')
    )
    op.create_index('idx_sales_product_date', 'sales', ['product_id', 'date'], unique=False)
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.drop_index('idx_sales_product_date', table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_offer_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_price_recommendations_status'), table_name='price_recommendations')
    op.drop_index(op.f('ix_price_recommendations_product_id'), table_name='price_recommendations')
    op.drop_table('price_recommendations')
    op.drop_index(op.f('ix_price_history_product_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_created_at'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_inventory_snapshot_date'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_review_date'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_product_id'), table_name='experiments')
    op.drop_table('experiments')
    # ### end Alembic commands ###
